version: "3"
services:
  gas:
    build: .
    volumes:
      - .:/workdir
      - ./.clasprc.json:/root/.clasprc.json
      - /workdir/node_modules
    working_dir: /workdir
    command: tail -f /dev/null
    ports:
      - 42157:42157
